apiVersion: v1
kind: Service
metadata:
  name: app-service-java
spec:
  type: NodePort
  selector:
    app: randomnumbergenerator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
