apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: randomnumbergenerator
  template:
    metadata:
      labels:
        app: randomnumbergenerator
    spec:
      containers:
      - name: randomnumbergenerator
        image: argendune/randomnumbergenerator:latest
        ports:
        - containerPort: 8080
